### ISSUE TITLE
Model Save not working for ner with lstm-crf

### ISSUE THREAD

**Issue by vignesh0710** [PacktPublishing/Advanced-Natural-Language-Processing-with-TensorFlow-2#1]
Sir, I bought your book and trying to learn ```chapter 3 -  NER with LSTM CRF ``` in which the code works great, but when I try to save the model using 

```
import tensorflow as tf
tf.keras.models.save_model(blc_model, FILE_PATH)
```
I am getting the following error:

`TypeError: zip argument #1 must support iteration`
in the following line of the ```call``` method in the class ```CRFLayer ```
`for logit, text_len in zip(inputs, seqlens):`

**Comment by bansala** [comment]
Can you please describe your environment? OS, Python version, TF version,
TFA version etc?

**Comment by vignesh0710** [comment]
Environment:

```
Jupyter notebook (MAC OS)
Python - 3.6.10
```
Tried 2 combos for Tensorflow and Tensorflow Addons
```
Tensorflow - (2.3.0) and Tensorflow Addons (0.11.2)
Tensorflow - (2.4.1) and Tensorflow Addons (0.12.1)
```

**Comment by bansala** [comment]
This code is tested on TF 2.3 and TFA 0.11.2. I am going to close the issue
as this issue is with an extension of the code and not in the code in the
book itself.
Please feel free to connect with me directly for help on extending code
from the book for other use cases.

**Comment by vignesh0710** [comment]
Sure Sir. Please let me know on how to connect with you?

**Comment by bansala** [comment]
You can find me on LinkedIn or Twitter. Feel free to dM me.
